name: Build spine-godot GDExtension (Godot 4.x)

on:
  workflow_call:
    inputs:
      godot_tag:
        required: true
        type: string
        default: "Godot tag not specified!"
      godot_version:
        required: true
        type: string
        default: "Godot version not specified!"
      godot_cpp_api_version:
        required: true
        type: string
        default: "Godot C++ API version not specified!"
      dev:
        required: true
        type: boolean
        default: false

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_EC2_METADATA_DISABLED: true
  GODOT_TAG: ${{ inputs.godot_tag }}
  GODOT_VERSION: ${{ inputs.godot_version }}
  GODOT_CPP_API_VERSION: ${{ inputs.godot_cpp_api_version }}
  DEV_BUILD: ${{ inputs.dev }}

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup python and scons
        uses: ./.github/actions/setup-godot-deps-4

      - name: Build GDExtension
        shell: bash
        run: |
          cd spine-godot/build
          ./setup-extension.sh $GODOT_TAG $DEV_BUILD
          ./build-extension.sh windows

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gdextension-windows-${{ env.GODOT_TAG }}
          path: spine-godot/example-v4-extension/bin/windows/*.dll
          retention-days: 7

  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup python and scons
        uses: ./.github/actions/setup-godot-deps-4

      - name: Build GDExtension
        run: |
          cd spine-godot/build
          ./setup-extension.sh $GODOT_TAG $DEV_BUILD
          ./build-extension.sh ios

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gdextension-ios-${{ env.GODOT_TAG }}
          path: spine-godot/example-v4-extension/bin/ios/**/*
          retention-days: 7

  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Make apt sources.list use the default Ubuntu repositories
        run: |
          sudo rm -f /etc/apt/sources.list.d/*
          sudo cp -f spine-godot/build/sources.lst /etc/apt/sources.list
          sudo apt-get update

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android SDK & NDK
        uses: android-actions/setup-android@v2

      - name: Install NDK
        run: |
          yes | sudo ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --licenses
          ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --install "ndk;28.1.13356709"

      - name: Setup python and scons
        uses: ./.github/actions/setup-godot-deps-4

      - name: Build GDExtension
        run: |
          cd spine-godot/build
          ./setup-extension.sh $GODOT_TAG $DEV_BUILD
          ANDROID_NDK_ROOT=$ANDROID_SDK_ROOT/ndk/28.1.13356709 ./build-extension.sh android
          ANDROID_NDK_ROOT=$ANDROID_SDK_ROOT/ndk/28.1.13356709 ./build-extension.sh android x86_64

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gdextension-android-${{ env.GODOT_TAG }}
          path: spine-godot/example-v4-extension/bin/android/*.so
          retention-days: 7

